name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # dispara quando fizer push na branch "main"

permissions:
  contents: write   # necessário para publicar no gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # use a versão do Node que seu projeto precisa

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build   # no React, a saída padrão é "build"
